-- ValenceOS · Phase 1 v2 — People CRM seed pack
-- ~25 personas across funds, founders, lawyers, internal team. Each row
-- references a fund by name (resolved via subquery) when applicable.
-- Idempotent on (full_name, company).

insert into public.people (
  full_name, role, company, fund_id, email, phone, linkedin_url,
  city, country,
  how_to_talk, relationship_history, what_they_care_about,
  favours_bank, things_to_avoid, mutuals,
  tags, last_touched_at
)
select
  v.full_name, v.role, v.company,
  (select id from public.funds f where f.name = v.fund_name limit 1) as fund_id,
  v.email, v.phone, v.linkedin_url,
  v.city, v.country,
  v.how_to_talk, v.relationship_history, v.what_they_care_about,
  v.favours_bank, v.things_to_avoid, v.mutuals,
  v.tags, v.last_touched_at
from (values
  -- Fund partners
  ('Anand Iyer',         'Principal',                  'Peak XV Partners',         'Peak XV Partners',
   'anand@peakxv.com',          '+91 98201 11111',  'https://linkedin.com/in/anand-iyer',
   'Bengaluru', 'India',
   'Direct, asks for cheque size in 30 seconds. Skip preamble.',
   'Met at IVCA 2019 via Trishant. Closed 2 deals together.',
   'Founder optionality. Path-to-IPO clarity.',
   'Will move fast for us. 2 of ~3 favours used.',
   'Don''t pitch on Mondays — they treat them as planning days.',
   'Close to Trishant. Distant from Manav.',
   array['Investor','VC','Hot'], current_date - 8),

  ('Devika Rao',         'Investment Director',        'Catamaran Ventures',       'Catamaran Ventures',
   'devika@catamaran.in',       '+91 98202 22222',  'https://linkedin.com/in/devika-rao',
   'Bengaluru', 'India',
   'Warm, prefers narrative pitches. Strong at the strategic question.',
   'Quarterly catch-up since 2021. Helped close Project Saffron.',
   'Brand quality. Founder coachability.',
   '1 of ~3 used. Last favour: warm intro to Premji team.',
   'Don''t bring junior team without warning.',
   'Close to Naina Lal.',
   array['Investor','Family Office','Warm'], current_date - 12),

  ('Naina Lal',          'Managing Director',          'Premji Invest',            'Premji Invest',
   'naina@premjiinvest.com',    '+91 98203 33333',  'https://linkedin.com/in/naina-lal',
   'Bengaluru', 'India',
   'Sharp and fast. Loves data. No fluff. Pre-read or no meeting.',
   'Knew her from BCG days. Met again at IVCA Conclave 2024.',
   'Unit economics. Path to defensibility.',
   '0 used. Hot relationship — guard it.',
   'No weekend emails. Don''t over-pitch.',
   'Close to Hemant Sahni.',
   array['Investor','Family Office','Hot'], current_date - 6),

  ('Karthik Iyer',       'Partner',                    'Blume Ventures',           'Blume Ventures',
   'karthik@blume.vc',          '+91 98204 44444',  'https://linkedin.com/in/karthik-iyer',
   'Mumbai', 'India',
   'Thoughtful. Will spend 90 minutes on a pitch if interested.',
   'Warm but stage too late for them historically.',
   'Founder team chemistry. Tech-led defensibility.',
   '0 used.',
   'Don''t pitch later-stage rounds.',
   'Close to Stephen Walker.',
   array['Investor','VC','Warm'], current_date - 14),

  ('Rhea Mathur',        'Partner',                    'Lightspeed India',         'Lightspeed India',
   'rhea@lightspeed.com',       '+91 98205 55555',  'https://linkedin.com/in/rhea-mathur',
   'Mumbai', 'India',
   'Casual, quick. Good at separating signal from noise.',
   'Met at TiE Mumbai 2022. Quarterly catch-up.',
   'Capital efficiency. Indian-born global stories.',
   '0 used. Worth saving.',
   'Don''t bring biotech.',
   '—',
   array['Investor','VC','Warm'], current_date - 11),

  ('Hemant Sahni',       'Partner',                    'Chiratae Ventures',        'Chiratae Ventures',
   'hemant@chiratae.com',       '+91 98206 66666',  'https://linkedin.com/in/hemant-sahni',
   'Bengaluru', 'India',
   'Warm and patient. Good listener. Engages on early-stage stories.',
   'Long-arc relationship since 2019.',
   'Healthcare deep tech. India-first stories.',
   '0 of ~3.',
   'Don''t pitch consumer tech without a clear MOAT.',
   'Close to Naina Lal.',
   array['Investor','VC','Warm'], current_date - 13),

  ('Yash Anand',         'Partner',                    'Kalaari Capital',          'Kalaari Capital',
   'yash@kalaari.com',          '+91 98217 00008',  null,
   'Bengaluru', 'India',
   'Polite, brand-conscious.',
   'Brand recall meetings.',
   'Founder pedigree.',
   '0 used.',
   'Don''t pitch what they''re not deploying for.',
   '—',
   array['Investor','VC','Distant'], current_date - 22),

  ('Lara Petrov',        'Principal',                  'Sequoia Capital India',    'Sequoia Capital',
   'lara@sequoia.com',          '+91 98216 00007',  null,
   'Bengaluru', 'India',
   'Curious. Asks broad questions before zooming in.',
   'Met at fintech roundtable.',
   'Distribution as a moat.',
   '0 used.',
   '—',
   '—',
   array['Investor','VC','Warm'], current_date - 9),

  ('Stephen Walker',     'Director, Capital Markets',  'Fidelity',                 null,
   'swalker@fidelity.com',      '+1 617 555 0101',  null,
   'Boston', 'USA',
   'Process-driven. Wants written briefs ahead of every call.',
   'Anchor on Quantum Edge. Continuing dialogue.',
   'Anchor allocation transparency. Aftermarket support.',
   '1 of ~2 used.',
   'Don''t share unverified financials.',
   'Close to Karthik Iyer.',
   array['Investor','Hot'], current_date - 1),

  ('Daniel Cheng',       'Director',                   'Tiger Global',             'Tiger Global',
   'daniel@tigerglobal.com',    '+1 212 555 0303',  null,
   'New York', 'USA',
   'Fast, transactional. Treats every meeting like a dealflow filter.',
   'Loose dialogue since 2020. Tracking growth-stage fintech.',
   'Growth rate. TAM. Unit economics.',
   '0 used.',
   'No biotech. No early-stage.',
   '—',
   array['Investor','Hot'], current_date - 2),

  ('Mark Rutherford',    'VP',                         'Brookfield Asset Management', 'Brookfield Asset Management',
   'mark@brookfield.com',       '+1 416 555 0202',  null,
   'Toronto', 'Canada',
   'Formal. Wants institutional-grade IMs. No shortcuts.',
   'Real estate + infra coverage. Met at MIPIM 2024.',
   'Yield. Counterparty quality. Regulatory clarity.',
   '0 used.',
   'Don''t pitch sub-$100M EV deals.',
   '—',
   array['Investor','PE','Warm'], current_date - 4),

  ('Nina Kapoor',        'Senior Investment Officer',  'GIC',                      'GIC',
   'nina@gic.com.sg',           '+65 6555 0404',    null,
   'Singapore', 'Singapore',
   'Institutional. Documents everything.',
   'Sovereign coverage map. Active for India infra + renewables.',
   'Long-tenor stable yields. ESG.',
   '0 of 1.',
   'Don''t pitch consumer or tech.',
   '—',
   array['Investor','Sovereign','Warm'], current_date - 11),

  -- Founders / clients
  ('Rohit Bansal',       'CEO',                        'Nimbus Health',            null,
   'rohit@nimbushealth.com',    '+91 98207 77777',  null,
   'Mumbai', 'India',
   'Founder pace. Texts late. Treats us like an extension of team.',
   'Sell-side mandate signed Q2.',
   'Strategic acquirer over PE. Family legacy.',
   'N/A — client.',
   'Don''t go to PE-only buyers without clearance.',
   '—',
   array['Founder','Hot'], current_date - 3),

  ('Vikas Subramanian',  'Founder & CEO',              'Meridian EdTech',          null,
   'vikas@meridianedu.com',     '+91 98208 88888',  null,
   'Bengaluru', 'India',
   'Earnest, careful. Wants weekly written updates.',
   'Series C mandate signed last month.',
   'Mission-aligned investors. EdTech-friendly term sheets.',
   'N/A — client.',
   'Don''t bring growth funds with media reputations for being aggressive.',
   '—',
   array['Founder','Hot'], current_date - 5),

  ('Tara Krishnan',      'CFO',                        'Solstice Solar',           null,
   'tara@solsticesolar.in',     '+91 98209 99999',  null,
   'Hyderabad', 'India',
   'Numbers-first. Wants the P&L story and unit economics in slide one.',
   'Series C raise in scoping. Sent credentials memo.',
   'Long-tenor capital. Strategic acquirers as plan B.',
   'N/A — client.',
   'No PR before closing.',
   'Plays golf with James Whitfield.',
   array['Founder','Warm'], current_date - 1),

  ('Maya Iyengar',       'Founder',                    'Kestrel Biotech',          null,
   'maya@kestrelbio.com',       '+91 98210 00001',  null,
   'Bengaluru', 'India',
   'Scientific. Loves the technical deep dive. Pitch in pre-clinical milestones.',
   'Buy-side scoping for licensing-deal acquisitions.',
   'Science before terms. Long-term partner mindset.',
   'N/A — client.',
   'Don''t reduce her pitch to financials.',
   '—',
   array['Founder','Warm'], current_date - 7),

  ('Ishaan Kapoor',      'Founder',                    'Saffron Retail',           null,
   'ishaan@saffronretail.in',   '+91 98211 00002',  null,
   'Mumbai', 'India',
   'Salesperson. High-energy. Loves the deal-chase part.',
   'Sell-side mandate. Sponsor in exclusivity.',
   'Headline number. Media coverage post-close.',
   'N/A — client.',
   'Don''t under-promise.',
   '—',
   array['Founder','Hot'], current_date - 6),

  ('Niharika Joshi',     'Group CFO',                  'Evermark Retail',          null,
   'niharika@evermark.in',      '+91 98212 00003',  null,
   'Delhi', 'India',
   'Calm, deliberate. Will say "let me come back to you" rather than commit on calls.',
   'Met at consumer summit Q4. Process kickoff scheduled.',
   'Strategic fit > valuation peak.',
   'N/A — client.',
   'Don''t loop in junior team during early conversations.',
   '—',
   array['Founder','Warm'], current_date - 7),

  ('Arvind Kulkarni',    'CFO',                        'Crescent Pharma',          null,
   'arvind@crescentpharma.in',  '+91 98219 00010',  null,
   'Hyderabad', 'India',
   'Methodical. Sends Excel before every call.',
   'OTC carve-out scoping.',
   'Strategic vs financial buyer mix.',
   'N/A — prospect.',
   'Don''t skip the regulatory diligence questions.',
   '—',
   array['Founder','Warm'], current_date - 2),

  -- Co-advisors / lawyers
  ('James Whitfield',    'Partner',                    'Whitfield & Co.',          null,
   'james@whitfield.co.uk',     '+44 20 7123 4567', null,
   'London', 'UK',
   'Old-school British. Drinks-on-the-Strand style. Long lunches.',
   'Inbound referrals only. Sent us Hyderabad CPG founder in Q1.',
   'Reciprocity. Send him deals back.',
   'Owes us 2. Delicate balance — his ego matters.',
   'Never call without an email first.',
   'Plays golf with the Solstice founders.',
   array['Co-advisor','Distant'], current_date - 7),

  ('Sophie Laurent',     'Founder',                    'Laurent Capital',          null,
   'sophie@laurentcap.fr',      '+33 1 555 0505',   null,
   'Paris', 'France',
   'Continental. Polite passes. Long emails.',
   'Loose referral loop. Closed an inbound out to a Paris boutique.',
   'Cross-border France-India.',
   '0 of 1.',
   '—',
   '—',
   array['Co-advisor','Distant'], current_date - 30),

  -- Family offices
  ('Aditya Sahay',       'Principal',                  'Sahay Family Office',      null,
   'aditya@sahayfo.com',        '+91 98213 00004',  null,
   'Mumbai', 'India',
   'Casual but structured. Brings the family principal in only when sure.',
   'Long-arc. Sent us small mid-cap mandate that we passed back.',
   'Generational wealth preservation.',
   '0 used.',
   'Don''t bring deals < $25M EV.',
   '—',
   array['Investor','Family Office','Warm'], current_date - 22),

  ('Rajat Bhatia',       'Principal',                  'Bhatia Family Office',     null,
   'rajat@bhatia.fo',           '+91 98214 00005',  null,
   'Mumbai', 'India',
   'Direct. Wants thesis in 5 lines.',
   'Inbound from existing client.',
   'Niche logistics. Single-asset exposure.',
   'N/A — fresh relationship.',
   'Don''t bring large funds; he prefers privacy.',
   '—',
   array['Investor','Family Office','Warm'], current_date - 5),

  -- Internal Valence team
  ('Trishant Patel',     'Managing Partner',           'Valence Growth Partners',  null,
   'trishant@valencegrowth.com','+91 98220 00011',  null,
   'Mumbai', 'India',
   'N/A — internal.', 'Founder. Internal.', '—', '—', '—', '—',
   array['Operator'], current_date),

  ('Manav Kapoor',       'Partner',                    'Valence Growth Partners',  null,
   'manav@valencegrowth.com',   '+91 98221 00012',  null,
   'London', 'UK',
   'N/A — internal.', 'Internal.', '—', '—', '—', '—',
   array['Operator'], current_date)
) as v(
  full_name, role, company, fund_name,
  email, phone, linkedin_url,
  city, country,
  how_to_talk, relationship_history, what_they_care_about,
  favours_bank, things_to_avoid, mutuals,
  tags, last_touched_at
)
where not exists (
  select 1 from public.people p where p.full_name = v.full_name and coalesce(p.company,'') = coalesce(v.company,'')
);
